"""Pre-populated demo data for WellnessFlow."""

from datetime import date, timedelta

SERVICE_TYPES = [
    {
        "id": "svc-001",
        "name": "60-Minute Massage",
        "duration_minutes": 60,
        "price": 120.00,
        "category": "massage",
    },
    {
        "id": "svc-002",
        "name": "90-Minute Massage",
        "duration_minutes": 90,
        "price": 160.00,
        "category": "massage",
    },
    {
        "id": "svc-003",
        "name": "Acupuncture Session",
        "duration_minutes": 60,
        "price": 95.00,
        "category": "acupuncture",
    },
    {
        "id": "svc-004",
        "name": "Nutrition Consultation",
        "duration_minutes": 45,
        "price": 85.00,
        "category": "nutrition",
    },
    {
        "id": "svc-005",
        "name": "Chiropractic Adjustment",
        "duration_minutes": 30,
        "price": 75.00,
        "category": "chiropractic",
    },
    {
        "id": "svc-006",
        "name": "Deep Tissue Massage",
        "duration_minutes": 60,
        "price": 140.00,
        "category": "massage",
    },
    {
        "id": "svc-007",
        "name": "Initial Nutrition Assessment",
        "duration_minutes": 60,
        "price": 110.00,
        "category": "nutrition",
    },
]

_svc_map = {s["id"]: s for s in SERVICE_TYPES}

CLIENTS = [
    {
        "id": "cli-001",
        "first_name": "Maria",
        "last_name": "Santos",
        "email": "maria.santos@email.com",
        "phone": "(415) 555-0101",
        "date_of_birth": "1985-03-14",
        "intake_date": "2025-06-10",
        "conditions": ["chronic back pain", "sciatica"],
        "insurance_provider": "Blue Cross",
        "insurance_id": "BC-882741",
        "notes": "Prefers afternoon appointments. Sensitive to deep pressure on lower back.",
    },
    {
        "id": "cli-002",
        "first_name": "James",
        "last_name": "O'Brien",
        "email": "james.obrien@email.com",
        "phone": "(415) 555-0102",
        "date_of_birth": "1978-09-22",
        "intake_date": "2025-08-15",
        "conditions": ["sports injury", "rotator cuff strain"],
        "insurance_provider": "Aetna",
        "insurance_id": "AET-447291",
        "notes": "Marathon runner. Needs work on shoulders and IT band.",
    },
    {
        "id": "cli-003",
        "first_name": "Aisha",
        "last_name": "Patel",
        "email": "aisha.patel@email.com",
        "phone": "(415) 555-0103",
        "date_of_birth": "1990-12-05",
        "intake_date": "2025-09-01",
        "conditions": ["stress", "anxiety", "tension headaches"],
        "insurance_provider": "United Healthcare",
        "insurance_id": "UHC-991034",
        "notes": "High-stress tech job. Responds well to acupuncture.",
    },
    {
        "id": "cli-004",
        "first_name": "David",
        "last_name": "Kim",
        "email": "david.kim@email.com",
        "phone": "(415) 555-0104",
        "date_of_birth": "1982-07-18",
        "intake_date": "2025-07-20",
        "conditions": ["herniated disc", "lower back pain"],
        "insurance_provider": "Kaiser",
        "insurance_id": "KP-554382",
        "notes": "Desk worker. Combined chiropractic and massage treatment plan.",
    },
    {
        "id": "cli-005",
        "first_name": "Elena",
        "last_name": "Rodriguez",
        "email": "elena.rodriguez@email.com",
        "phone": "(415) 555-0105",
        "date_of_birth": "1995-01-30",
        "intake_date": "2025-11-05",
        "conditions": ["prenatal", "lower back pain", "hip pain"],
        "insurance_provider": "Blue Shield",
        "insurance_id": "BS-773521",
        "notes": "Currently 28 weeks pregnant. Side-lying position only.",
    },
    {
        "id": "cli-006",
        "first_name": "Robert",
        "last_name": "Thompson",
        "email": "robert.thompson@email.com",
        "phone": "(415) 555-0106",
        "date_of_birth": "1968-11-12",
        "intake_date": "2025-05-18",
        "conditions": ["post-surgery rehab", "knee replacement"],
        "insurance_provider": "Cigna",
        "insurance_id": "CIG-228491",
        "notes": "Right knee replacement Nov 2025. Cleared for massage around surgical site.",
    },
    {
        "id": "cli-007",
        "first_name": "Yuki",
        "last_name": "Tanaka",
        "email": "yuki.tanaka@email.com",
        "phone": "(415) 555-0107",
        "date_of_birth": "1992-04-25",
        "intake_date": "2025-10-12",
        "conditions": ["migraines", "neck tension"],
        "insurance_provider": "Aetna",
        "insurance_id": "AET-662103",
        "notes": "Migraines 3-4x/month. Acupuncture has reduced frequency significantly.",
    },
    {
        "id": "cli-008",
        "first_name": "Marcus",
        "last_name": "Johnson",
        "email": "marcus.johnson@email.com",
        "phone": "(415) 555-0108",
        "date_of_birth": "1987-06-08",
        "intake_date": "2026-01-10",
        "conditions": ["weight management", "pre-diabetes"],
        "insurance_provider": None,
        "insurance_id": None,
        "notes": "Self-pay. Nutrition coaching for weight loss and blood sugar management.",
    },
    {
        "id": "cli-009",
        "first_name": "Sophie",
        "last_name": "Laurent",
        "email": "sophie.laurent@email.com",
        "phone": "(415) 555-0109",
        "date_of_birth": "1975-08-19",
        "intake_date": "2025-12-01",
        "conditions": ["fibromyalgia", "chronic fatigue"],
        "insurance_provider": "Blue Cross",
        "insurance_id": "BC-441289",
        "notes": "Very light pressure only. Flare-ups in cold weather.",
    },
    {
        "id": "cli-010",
        "first_name": "Carlos",
        "last_name": "Mendez",
        "email": "carlos.mendez@email.com",
        "phone": "(415) 555-0110",
        "date_of_birth": "1999-02-14",
        "intake_date": "2026-02-01",
        "conditions": ["sports injury", "ankle sprain"],
        "insurance_provider": "United Healthcare",
        "insurance_id": "UHC-887452",
        "notes": "College soccer player. Needs clearance before return to play.",
    },
    {
        "id": "cli-011",
        "first_name": "Linda",
        "last_name": "Nguyen",
        "email": "linda.nguyen@email.com",
        "phone": "(415) 555-0111",
        "date_of_birth": "1970-10-03",
        "intake_date": "2025-04-22",
        "conditions": ["arthritis", "joint stiffness"],
        "insurance_provider": "Kaiser",
        "insurance_id": "KP-339517",
        "notes": "Osteoarthritis in both hands and right knee. Gentle mobilization.",
    },
    {
        "id": "cli-012",
        "first_name": "Alex",
        "last_name": "Rivera",
        "email": "alex.rivera@email.com",
        "phone": "(415) 555-0112",
        "date_of_birth": "1988-05-27",
        "intake_date": "2026-03-01",
        "conditions": ["digestive issues", "food sensitivities"],
        "insurance_provider": None,
        "insurance_id": None,
        "notes": "Self-pay. Elimination diet protocol. Follow-up in 4 weeks.",
    },
]

# Today reference for generating realistic dates
_today = date(2026, 3, 26)

APPOINTMENTS = [
    # Past — completed
    {
        "id": "apt-001",
        "client_id": "cli-001",
        "client_name": "Maria Santos",
        "service_type": "60-Minute Massage",
        "service_category": "massage",
        "date": (_today - timedelta(days=14)).isoformat(),
        "time": "10:00",
        "duration_minutes": 60,
        "status": "completed",
        "price": 120.00,
        "notes": "Focused on lower back and glutes. Client reports 40% pain reduction.",
    },
    {
        "id": "apt-002",
        "client_id": "cli-002",
        "client_name": "James O'Brien",
        "service_type": "Deep Tissue Massage",
        "service_category": "massage",
        "date": (_today - timedelta(days=12)).isoformat(),
        "time": "14:00",
        "duration_minutes": 60,
        "status": "completed",
        "price": 140.00,
        "notes": "Rotator cuff work. Improved ROM by 15 degrees.",
    },
    {
        "id": "apt-003",
        "client_id": "cli-003",
        "client_name": "Aisha Patel",
        "service_type": "Acupuncture Session",
        "service_category": "acupuncture",
        "date": (_today - timedelta(days=10)).isoformat(),
        "time": "11:00",
        "duration_minutes": 60,
        "status": "completed",
        "price": 95.00,
        "notes": "Stress protocol — LI4, LV3, GV20, HT7. Deep relaxation achieved.",
    },
    {
        "id": "apt-004",
        "client_id": "cli-004",
        "client_name": "David Kim",
        "service_type": "Chiropractic Adjustment",
        "service_category": "chiropractic",
        "date": (_today - timedelta(days=9)).isoformat(),
        "time": "09:00",
        "duration_minutes": 30,
        "status": "completed",
        "price": 75.00,
        "notes": "L4-L5 adjustment. Decompression exercises assigned.",
    },
    {
        "id": "apt-005",
        "client_id": "cli-005",
        "client_name": "Elena Rodriguez",
        "service_type": "60-Minute Massage",
        "service_category": "massage",
        "date": (_today - timedelta(days=8)).isoformat(),
        "time": "13:00",
        "duration_minutes": 60,
        "status": "completed",
        "price": 120.00,
        "notes": "Prenatal massage. Side-lying. Focused on lower back and hip flexors.",
    },
    {
        "id": "apt-006",
        "client_id": "cli-006",
        "client_name": "Robert Thompson",
        "service_type": "60-Minute Massage",
        "service_category": "massage",
        "date": (_today - timedelta(days=7)).isoformat(),
        "time": "15:00",
        "duration_minutes": 60,
        "status": "completed",
        "price": 120.00,
        "notes": "Post-surgical rehab. Gentle work around right knee. Quad release.",
    },
    {
        "id": "apt-007",
        "client_id": "cli-007",
        "client_name": "Yuki Tanaka",
        "service_type": "Acupuncture Session",
        "service_category": "acupuncture",
        "date": (_today - timedelta(days=5)).isoformat(),
        "time": "10:30",
        "duration_minutes": 60,
        "status": "completed",
        "price": 95.00,
        "notes": "Migraine protocol. Only 1 migraine this week vs. usual 3-4.",
    },
    {
        "id": "apt-008",
        "client_id": "cli-008",
        "client_name": "Marcus Johnson",
        "service_type": "Nutrition Consultation",
        "service_category": "nutrition",
        "date": (_today - timedelta(days=4)).isoformat(),
        "time": "16:00",
        "duration_minutes": 45,
        "status": "completed",
        "price": 85.00,
        "notes": "Week 10 check-in. Down 12lbs. A1C improved from 6.1 to 5.7.",
    },
    {
        "id": "apt-009",
        "client_id": "cli-009",
        "client_name": "Sophie Laurent",
        "service_type": "90-Minute Massage",
        "service_category": "massage",
        "date": (_today - timedelta(days=3)).isoformat(),
        "time": "11:00",
        "duration_minutes": 90,
        "status": "completed",
        "price": 160.00,
        "notes": "Full-body light pressure. Myofascial release on thoracic spine.",
    },
    {
        "id": "apt-010",
        "client_id": "cli-010",
        "client_name": "Carlos Mendez",
        "service_type": "Chiropractic Adjustment",
        "service_category": "chiropractic",
        "date": (_today - timedelta(days=2)).isoformat(),
        "time": "08:30",
        "duration_minutes": 30,
        "status": "completed",
        "price": 75.00,
        "notes": "Ankle mobility assessment. 80% recovered. 2 more sessions.",
    },
    # Past — cancelled / no-show
    {
        "id": "apt-011",
        "client_id": "cli-011",
        "client_name": "Linda Nguyen",
        "service_type": "Acupuncture Session",
        "service_category": "acupuncture",
        "date": (_today - timedelta(days=6)).isoformat(),
        "time": "14:00",
        "duration_minutes": 60,
        "status": "cancelled",
        "price": 95.00,
        "notes": "Client called day before — flu symptoms.",
    },
    {
        "id": "apt-012",
        "client_id": "cli-012",
        "client_name": "Alex Rivera",
        "service_type": "Nutrition Consultation",
        "service_category": "nutrition",
        "date": (_today - timedelta(days=3)).isoformat(),
        "time": "09:00",
        "duration_minutes": 45,
        "status": "no_show",
        "price": 85.00,
        "notes": "No-show. Attempted to reach by phone.",
    },
    # Upcoming — scheduled
    {
        "id": "apt-013",
        "client_id": "cli-001",
        "client_name": "Maria Santos",
        "service_type": "60-Minute Massage",
        "service_category": "massage",
        "date": _today.isoformat(),
        "time": "14:00",
        "duration_minutes": 60,
        "status": "scheduled",
        "price": 120.00,
        "notes": "Continue lower back protocol.",
    },
    {
        "id": "apt-014",
        "client_id": "cli-003",
        "client_name": "Aisha Patel",
        "service_type": "Acupuncture Session",
        "service_category": "acupuncture",
        "date": _today.isoformat(),
        "time": "16:00",
        "duration_minutes": 60,
        "status": "scheduled",
        "price": 95.00,
        "notes": "Follow-up stress protocol.",
    },
    {
        "id": "apt-015",
        "client_id": "cli-004",
        "client_name": "David Kim",
        "service_type": "Chiropractic Adjustment",
        "service_category": "chiropractic",
        "date": (_today + timedelta(days=1)).isoformat(),
        "time": "09:00",
        "duration_minutes": 30,
        "status": "scheduled",
        "price": 75.00,
        "notes": "Bi-weekly adjustment.",
    },
    {
        "id": "apt-016",
        "client_id": "cli-005",
        "client_name": "Elena Rodriguez",
        "service_type": "60-Minute Massage",
        "service_category": "massage",
        "date": (_today + timedelta(days=2)).isoformat(),
        "time": "11:00",
        "duration_minutes": 60,
        "status": "scheduled",
        "price": 120.00,
        "notes": "Prenatal session. Check in on hip pain.",
    },
    {
        "id": "apt-017",
        "client_id": "cli-007",
        "client_name": "Yuki Tanaka",
        "service_type": "Acupuncture Session",
        "service_category": "acupuncture",
        "date": (_today + timedelta(days=2)).isoformat(),
        "time": "14:30",
        "duration_minutes": 60,
        "status": "scheduled",
        "price": 95.00,
        "notes": "Migraine maintenance session.",
    },
    {
        "id": "apt-018",
        "client_id": "cli-008",
        "client_name": "Marcus Johnson",
        "service_type": "Nutrition Consultation",
        "service_category": "nutrition",
        "date": (_today + timedelta(days=3)).isoformat(),
        "time": "10:00",
        "duration_minutes": 45,
        "status": "scheduled",
        "price": 85.00,
        "notes": "Bi-weekly nutrition check-in.",
    },
    {
        "id": "apt-019",
        "client_id": "cli-011",
        "client_name": "Linda Nguyen",
        "service_type": "Acupuncture Session",
        "service_category": "acupuncture",
        "date": (_today + timedelta(days=4)).isoformat(),
        "time": "13:00",
        "duration_minutes": 60,
        "status": "scheduled",
        "price": 95.00,
        "notes": "Rescheduled from cancelled appointment.",
    },
    {
        "id": "apt-020",
        "client_id": "cli-002",
        "client_name": "James O'Brien",
        "service_type": "90-Minute Massage",
        "service_category": "massage",
        "date": (_today + timedelta(days=5)).isoformat(),
        "time": "15:00",
        "duration_minutes": 90,
        "status": "scheduled",
        "price": 160.00,
        "notes": "Pre-marathon prep. Full body focus.",
    },
]

TREATMENT_PLANS = [
    {
        "id": "tp-001",
        "client_id": "cli-001",
        "client_name": "Maria Santos",
        "plan_type": "Massage Therapy",
        "condition": "Chronic back pain & sciatica",
        "total_sessions": 12,
        "completed_sessions": 8,
        "start_date": "2025-10-01",
        "next_session": _today.isoformat(),
        "goals": [
            "Reduce pain from 7/10 to 3/10",
            "Improve lumbar flexibility",
            "Return to regular exercise",
        ],
        "notes": "Good progress. Pain currently at 4/10.",
    },
    {
        "id": "tp-002",
        "client_id": "cli-002",
        "client_name": "James O'Brien",
        "plan_type": "Sports Rehabilitation",
        "condition": "Rotator cuff strain",
        "total_sessions": 8,
        "completed_sessions": 5,
        "start_date": "2025-12-15",
        "next_session": (_today + timedelta(days=5)).isoformat(),
        "goals": [
            "Restore full shoulder ROM",
            "Strengthen rotator cuff",
            "Return to marathon training",
        ],
        "notes": "ROM improved 70%. On track for April marathon.",
    },
    {
        "id": "tp-003",
        "client_id": "cli-003",
        "client_name": "Aisha Patel",
        "plan_type": "Acupuncture Protocol",
        "condition": "Stress, anxiety & tension headaches",
        "total_sessions": 10,
        "completed_sessions": 6,
        "start_date": "2025-11-01",
        "next_session": _today.isoformat(),
        "goals": [
            "Reduce headache frequency by 75%",
            "Improve sleep quality",
            "Lower perceived stress level",
        ],
        "notes": "Headaches down from 4x/week to 1x/week. Sleep improved.",
    },
    {
        "id": "tp-004",
        "client_id": "cli-004",
        "client_name": "David Kim",
        "plan_type": "Chiropractic + Massage",
        "condition": "Herniated disc L4-L5",
        "total_sessions": 16,
        "completed_sessions": 10,
        "start_date": "2025-09-15",
        "next_session": (_today + timedelta(days=1)).isoformat(),
        "goals": [
            "Reduce disc compression symptoms",
            "Strengthen core stability",
            "Ergonomic workstation setup",
        ],
        "notes": "MRI shows 30% disc improvement. Core exercises compliant.",
    },
    {
        "id": "tp-005",
        "client_id": "cli-006",
        "client_name": "Robert Thompson",
        "plan_type": "Post-Surgical Rehab",
        "condition": "Right knee replacement recovery",
        "total_sessions": 20,
        "completed_sessions": 14,
        "start_date": "2025-11-20",
        "next_session": (_today + timedelta(days=7)).isoformat(),
        "goals": [
            "Achieve 120-degree knee flexion",
            "Independent stair climbing",
            "Return to daily walks",
        ],
        "notes": "Currently at 105-degree flexion. Walking 1 mile/day.",
    },
    {
        "id": "tp-006",
        "client_id": "cli-007",
        "client_name": "Yuki Tanaka",
        "plan_type": "Migraine Management",
        "condition": "Chronic migraines",
        "total_sessions": 12,
        "completed_sessions": 7,
        "start_date": "2025-10-15",
        "next_session": (_today + timedelta(days=2)).isoformat(),
        "goals": [
            "Reduce migraine frequency to 1x/month",
            "Identify and avoid triggers",
            "Decrease medication dependency",
        ],
        "notes": "Down to 1-2 migraines/month from 3-4/week. Excellent progress.",
    },
    {
        "id": "tp-007",
        "client_id": "cli-008",
        "client_name": "Marcus Johnson",
        "plan_type": "Nutrition Coaching",
        "condition": "Weight management & pre-diabetes",
        "total_sessions": 12,
        "completed_sessions": 5,
        "start_date": "2026-01-10",
        "next_session": (_today + timedelta(days=3)).isoformat(),
        "goals": [
            "Lose 30lbs over 6 months",
            "Normalize A1C below 5.7",
            "Establish sustainable meal prep routine",
        ],
        "notes": "Down 12lbs. A1C improved 6.1 -> 5.7. Meal prepping 4 days/week.",
    },
    {
        "id": "tp-008",
        "client_id": "cli-010",
        "client_name": "Carlos Mendez",
        "plan_type": "Sports Injury Recovery",
        "condition": "Grade 2 ankle sprain",
        "total_sessions": 6,
        "completed_sessions": 4,
        "start_date": "2026-02-10",
        "next_session": (_today + timedelta(days=6)).isoformat(),
        "goals": [
            "Full weight-bearing without pain",
            "Restore proprioception",
            "Return to soccer clearance",
        ],
        "notes": "80% recovered. Balance exercises progressing well.",
    },
]

INSURANCE_CLAIMS = [
    {
        "id": "clm-001",
        "client_id": "cli-001",
        "client_name": "Maria Santos",
        "appointment_id": "apt-001",
        "service_type": "60-Minute Massage",
        "date_of_service": (_today - timedelta(days=14)).isoformat(),
        "amount": 120.00,
        "insurance_provider": "Blue Cross",
        "status": "paid",
        "submitted_date": (_today - timedelta(days=13)).isoformat(),
        "paid_date": (_today - timedelta(days=3)).isoformat(),
        "paid_amount": 96.00,
    },
    {
        "id": "clm-002",
        "client_id": "cli-002",
        "client_name": "James O'Brien",
        "appointment_id": "apt-002",
        "service_type": "Deep Tissue Massage",
        "date_of_service": (_today - timedelta(days=12)).isoformat(),
        "amount": 140.00,
        "insurance_provider": "Aetna",
        "status": "paid",
        "submitted_date": (_today - timedelta(days=11)).isoformat(),
        "paid_date": (_today - timedelta(days=1)).isoformat(),
        "paid_amount": 112.00,
    },
    {
        "id": "clm-003",
        "client_id": "cli-003",
        "client_name": "Aisha Patel",
        "appointment_id": "apt-003",
        "service_type": "Acupuncture Session",
        "date_of_service": (_today - timedelta(days=10)).isoformat(),
        "amount": 95.00,
        "insurance_provider": "United Healthcare",
        "status": "paid",
        "submitted_date": (_today - timedelta(days=9)).isoformat(),
        "paid_date": (_today - timedelta(days=2)).isoformat(),
        "paid_amount": 76.00,
    },
    {
        "id": "clm-004",
        "client_id": "cli-004",
        "client_name": "David Kim",
        "appointment_id": "apt-004",
        "service_type": "Chiropractic Adjustment",
        "date_of_service": (_today - timedelta(days=9)).isoformat(),
        "amount": 75.00,
        "insurance_provider": "Kaiser",
        "status": "approved",
        "submitted_date": (_today - timedelta(days=8)).isoformat(),
    },
    {
        "id": "clm-005",
        "client_id": "cli-005",
        "client_name": "Elena Rodriguez",
        "appointment_id": "apt-005",
        "service_type": "60-Minute Massage",
        "date_of_service": (_today - timedelta(days=8)).isoformat(),
        "amount": 120.00,
        "insurance_provider": "Blue Shield",
        "status": "under_review",
        "submitted_date": (_today - timedelta(days=7)).isoformat(),
    },
    {
        "id": "clm-006",
        "client_id": "cli-006",
        "client_name": "Robert Thompson",
        "appointment_id": "apt-006",
        "service_type": "60-Minute Massage",
        "date_of_service": (_today - timedelta(days=7)).isoformat(),
        "amount": 120.00,
        "insurance_provider": "Cigna",
        "status": "submitted",
        "submitted_date": (_today - timedelta(days=6)).isoformat(),
    },
    {
        "id": "clm-007",
        "client_id": "cli-007",
        "client_name": "Yuki Tanaka",
        "appointment_id": "apt-007",
        "service_type": "Acupuncture Session",
        "date_of_service": (_today - timedelta(days=5)).isoformat(),
        "amount": 95.00,
        "insurance_provider": "Aetna",
        "status": "submitted",
        "submitted_date": (_today - timedelta(days=4)).isoformat(),
    },
    {
        "id": "clm-008",
        "client_id": "cli-009",
        "client_name": "Sophie Laurent",
        "appointment_id": "apt-009",
        "service_type": "90-Minute Massage",
        "date_of_service": (_today - timedelta(days=3)).isoformat(),
        "amount": 160.00,
        "insurance_provider": "Blue Cross",
        "status": "submitted",
        "submitted_date": (_today - timedelta(days=2)).isoformat(),
    },
    {
        "id": "clm-009",
        "client_id": "cli-010",
        "client_name": "Carlos Mendez",
        "appointment_id": "apt-010",
        "service_type": "Chiropractic Adjustment",
        "date_of_service": (_today - timedelta(days=2)).isoformat(),
        "amount": 75.00,
        "insurance_provider": "United Healthcare",
        "status": "submitted",
        "submitted_date": (_today - timedelta(days=1)).isoformat(),
    },
    {
        "id": "clm-010",
        "client_id": "cli-011",
        "client_name": "Linda Nguyen",
        "appointment_id": "apt-011",
        "service_type": "Acupuncture Session",
        "date_of_service": (_today - timedelta(days=20)).isoformat(),
        "amount": 95.00,
        "insurance_provider": "Kaiser",
        "status": "denied",
        "submitted_date": (_today - timedelta(days=19)).isoformat(),
        "denial_reason": "Service not covered under current plan.",
    },
]

COMPLIANCE_ITEMS = [
    {
        "id": "comp-001",
        "name": "HIPAA Privacy Training",
        "category": "Training",
        "status": "current",
        "issue_date": "2025-06-01",
        "expiry_date": "2026-06-01",
        "notes": "Annual HIPAA compliance training completed via MedTrainer.",
    },
    {
        "id": "comp-002",
        "name": "CPR/First Aid Certification",
        "category": "Certification",
        "status": "current",
        "issue_date": "2025-03-15",
        "expiry_date": "2027-03-15",
        "notes": "American Red Cross BLS certification.",
    },
    {
        "id": "comp-003",
        "name": "California Massage Therapy License",
        "category": "License",
        "status": "current",
        "issue_date": "2024-09-01",
        "expiry_date": "2026-09-01",
        "notes": "CAMTC Certification #78234. 24 CEUs required for renewal.",
    },
    {
        "id": "comp-004",
        "name": "Acupuncture License — CA",
        "category": "License",
        "status": "expiring_soon",
        "issue_date": "2024-05-01",
        "expiry_date": "2026-05-01",
        "notes": "California Acupuncture Board. Renewal application submitted.",
    },
    {
        "id": "comp-005",
        "name": "Professional Liability Insurance",
        "category": "Insurance",
        "status": "current",
        "issue_date": "2025-07-01",
        "expiry_date": "2026-07-01",
        "notes": "ABMP policy. $2M/$6M coverage.",
    },
    {
        "id": "comp-006",
        "name": "Business Permit — San Francisco",
        "category": "Permit",
        "status": "current",
        "issue_date": "2025-01-01",
        "expiry_date": "2026-12-31",
        "notes": "Annual business registration with SF Treasurer.",
    },
    {
        "id": "comp-007",
        "name": "Nutrition Counseling Certification",
        "category": "Certification",
        "status": "current",
        "issue_date": "2025-08-01",
        "expiry_date": "2027-08-01",
        "notes": "NASM Certified Nutrition Coach. 20 CEUs/cycle.",
    },
    {
        "id": "comp-008",
        "name": "Bloodborne Pathogen Training",
        "category": "Training",
        "status": "expiring_soon",
        "issue_date": "2025-04-15",
        "expiry_date": "2026-04-15",
        "notes": "OSHA annual training requirement. Schedule renewal.",
    },
]

REVENUE_BY_MONTH = [
    {"month": "2025-04", "revenue": 4850.00},
    {"month": "2025-05", "revenue": 5320.00},
    {"month": "2025-06", "revenue": 5680.00},
    {"month": "2025-07", "revenue": 6100.00},
    {"month": "2025-08", "revenue": 5950.00},
    {"month": "2025-09", "revenue": 6400.00},
    {"month": "2025-10", "revenue": 6750.00},
    {"month": "2025-11", "revenue": 7100.00},
    {"month": "2025-12", "revenue": 6800.00},
    {"month": "2026-01", "revenue": 7350.00},
    {"month": "2026-02", "revenue": 7680.00},
    {"month": "2026-03", "revenue": 5240.00},  # partial month
]
